<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Lenovo-Laptop" name="com.fufang.testcase.ep.supplierapi.PullPharmacy" tests="2" failures="0" timestamp="13 Jan 2017 06:38:39 GMT" time="0.162" errors="1">
  <testcase name="savePharmacy" time="0.079" classname="com.fufang.testcase.ep.supplierapi.PullPharmacy">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;添加或修改药店成功。添加[[1]修改[0]]&gt; but was:&lt;添加或修改药店成功。添加[[0]修改[1]]&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<添加或修改药店成功。添加[[1]修改[0]]]]><![CDATA[> but was:<添加或修改药店成功。添加[[0]修改[1]]]]><![CDATA[>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at com.fufang.testcase.ep.supplierapi.PullPharmacy.savePharmacy(PullPharmacy.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- savePharmacy -->
  <testcase name="updatePharmacy" time="0.083" classname="com.fufang.testcase.ep.supplierapi.PullPharmacy"/>
</testsuite> <!-- com.fufang.testcase.ep.supplierapi.PullPharmacy -->
